# Template for GITHUB
configuration:
  origin:
    type: github
    urlBase: https://raw.githubusercontent.com/meiserBGamboa/public-docs-yaml
    branch: main
    directory: '/src/docs'
  documents:
    - path: nintendo
      name: nintendo
      file: './nintendo.yaml'
      default: true
    - path: nintendo-2
      name: nintendo-two
      file: './shopify.yaml'
    - path: nintendo-3
      name: nintendo-tree
      file: './nintendo.yaml'
    - path: nintendo-4
      name: nintendo-four
      file: './shopify.yaml'
    
